#**Digit Recognition**

## Mnist Datasets
> This is a dataset of 60,000 28x28 grayscale images of the 10 digits, along with a test set of 10,000 images.

In [ ]:
from keras.datasets import mnist

In [ ]:
# Fetching the dataset
(train_X, train_y), (test_X, test_y) = mnist.load_data()

In [ ]:
print('X_train: ', train_X.shape)
print('Y_train: ', train_y.shape)

X_train:  (60000, 28, 28)
Y_train:  (60000,)


In [ ]:
#Reshaping X Training set to fit the models
train_X_2D = train_X.reshape(60000,-1)

In [ ]:
print('X_train: ', train_X_2D.shape)
print('Y_train: ', train_y.shape)

X_train:  (60000, 784)
Y_train:  (60000,)


In [ ]:
print('X_test: ' ,test_X.shape)
print('Y_test: ' ,test_y.shape)

X_test:  (10000, 28, 28)
Y_test:  (10000,)


In [ ]:
#Reshaping X Testing set to fit the models
test_X_2D = test_X.reshape(10000, -1)

In [ ]:
print('X_test: ', test_X_2D.shape)
print('Y_test: ', test_y.shape)

X_test:  (10000, 784)
Y_test:  (10000,)


##Logistic Rgression Model

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
(train_X_logMdl, train_y_logMdl), (test_X_logMdl, test_y_logMdl) = (train_X_2D, train_y), (test_X_2D, test_y)

In [ ]:
# Logistic Model
logistic_mdl = LogisticRegression()

# Train the model
logistic_mdl.fit(train_X_logMdl, train_y_logMdl)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression()

In [ ]:
# Make predictions on the test set
y_pred_logMdl = logistic_mdl.predict(test_X_logMdl)

In [ ]:
# Accuracy Score
print("Accuracy: ", accuracy_score(test_y_logMdl, y_pred_logMdl))

# Classification Report
print("\n")
print("Classification Report:\n")
print(classification_report(test_y_logMdl, y_pred_logMdl))

# Confussion Matrix
print("Confusion Matrix:\n")
print(confusion_matrix(test_y, y_pred_logMdl))

Accuracy:  0.9255
Classification Report:

              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.97      1135
           2       0.93      0.90      0.91      1032
           3       0.90      0.91      0.91      1010
           4       0.93      0.93      0.93       982
           5       0.90      0.87      0.89       892
           6       0.94      0.95      0.95       958
           7       0.93      0.93      0.93      1028
           8       0.87      0.89      0.88       974
           9       0.91      0.91      0.91      1009

    accuracy                           0.93     10000
   macro avg       0.92      0.92      0.92     10000
weighted avg       0.93      0.93      0.93     10000

Confusion Matrix:

[[ 963    0    0    3    1    3    4    4    2    0]
 [   0 1112    4    2    0    1    3    2   11    0]
 [   3   10  926   15    6    4   15    8   42    3]
 [   4    1   21  916

##Decision Trees Model

In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
(train_X_DTmodel, train_y_DTmodel), (test_X_DTmodel, test_y_DTmodel) = (train_X_2D, train_y), (test_X_2D, test_y)

In [ ]:
# Deciosion Tree Model
clf = DecisionTreeClassifier()

# Training Model
clf.fit(train_X_DTmodel, train_y_DTmodel)

DecisionTreeClassifier()

In [ ]:
# Making prediction on test set
y_pred_DTmodel = clf.predict(test_X_DTmodel)

In [ ]:
# Accuracy Score
print("Accuracy: ", accuracy_score(test_y_DTmodel, y_pred_DTmodel))

# Classificatio report
print("\n")
print("Classification Report:\n")
print(classification_report(test_y_DTmodel, y_pred_DTmodel))

# Confusion Matrix
print("\n")
print("Confusion Matrix:\n")
print(confusion_matrix(test_y_DTmodel, y_pred_DTmodel))

Accuracy:  0.8781


Classification Report:

              precision    recall  f1-score   support

           0       0.93      0.94      0.93       980
           1       0.95      0.96      0.96      1135
           2       0.87      0.86      0.87      1032
           3       0.84      0.85      0.84      1010
           4       0.87      0.88      0.87       982
           5       0.82      0.83      0.83       892
           6       0.89      0.88      0.89       958
           7       0.92      0.90      0.91      1028
           8       0.82      0.80      0.81       974
           9       0.85      0.85      0.85      1009

    accuracy                           0.88     10000
   macro avg       0.88      0.88      0.88     10000
weighted avg       0.88      0.88      0.88     10000



Confusion Matrix:

[[ 921    1    7   10    3   13   12    3    7    3]
 [   2 1093   10    5    1    5    7    3    7    2]
 [  11   12  885   30   12   14   12   27   18   11]
 [   6    9   28 

## Support Vector Machines (SVM)

In [ ]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [ ]:
# Using smaller Datasets to reduce training time

(train_X_svmMdl, train_y_svmMdl), (test_X_svmMdl, test_y_svmMdl) = (train_X_2D[:20000], train_y[:20000]), (test_X_2D[:20000], test_y[:20000])

In [ ]:
# Training svm model using Polynomial Kernel
svm_Mdl = SVC(kernel = "rbf")
svm_Mdl.fit(train_X_svmMdl, train_y_svmMdl)

SVC()

In [ ]:
# Making pridiction on test set
y_pred_svmMdl = svm_Mdl.predict(test_X_svmMdl)

In [ ]:
# Accuracy Score
print("Accuracy: ", accuracy_score(test_y_svmMdl, y_pred_svmMdl))

# Classification Report
print("\n")
print("Classification Report:\n")
print(classification_report(test_y_svmMdl, y_pred_svmMdl))

# Confusion Matrix
print("\n")
print("Confusion Matrix:\n")
print(confusion_matrix(test_y_svmMdl, y_pred_svmMdl))

Accuracy:  0.9695


Classification Report:

              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       0.98      0.99      0.99      1135
           2       0.97      0.97      0.97      1032
           3       0.96      0.97      0.96      1010
           4       0.97      0.97      0.97       982
           5       0.97      0.96      0.97       892
           6       0.98      0.98      0.98       958
           7       0.97      0.95      0.96      1028
           8       0.96      0.96      0.96       974
           9       0.97      0.95      0.96      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000



Confusion Matrix:

[[ 969    0    1    0    0    3    4    1    2    0]
 [   0 1124    3    2    0    2    1    1    2    0]
 [   5    0 1001    1    4    0    2   10    9    0]
 [   0    0    5 